### ISSUE TITLE
encoding URL issue - android app

### ISSUE THREAD

**Issue by RiqueAM** [laiiihz/alga#5]
First of all, I thank you deeply for bringing this tool that helps a lot of people's daily tasks! May you be blessed for that!

For URL decoding it works great, but for encoding it doesn't work properly.

Example of how it should work:
Input:
H+4sIAGLWTWMA/7NRdPF3DokMQMAKykNUQ8AAAA=

Output:
H%2B4sIAGLWTWMA%2F7NRdPF3DokMQMAKykNUQ8AAAA%3D%0A

As is:
Output:
H+4sIAGLWTWMA/7NRdPF3DokMQMAKykNUQ8AAAA=

The characters "+/=" are not converting at all. From what I could tell, the app is actually only converting spaces and line breaks. I haven't tested the other characters, but I think it's all broken.

Here's a good site to test URL encode and decode:
https://www.urlencoder.org

**Comment by RiqueAM** [comment]
> i'll look into this 🙌 now only support encode/decode full uri ,next version will add a option for encode/decode uri component and uri query component.

I don't understand what you mean, I just use it and I've always needed to use URL encode and decode and I've never seen it this way. I'll try to compile with the fix as default in a fork.

**Comment by laiiihz** [comment]
sorry for not explained clearly, 
for example:
   the default encode/decode uri will not encode/decode those characters `A-Z a-z 0-9 ; , / ? : @ & = + $ - _ . ! ~ * ' ( ) #` ,[detail](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI).
  and in your situation, i'll provider a option which called `encode uri component`, that encoder/decoder will encode/decode all characters excepts `A-Z a-z 0-9 - _ . ! ~ * ' ( )`.
input:
```
H+4sIAGLWTWMA/7NRdPF3DokMQMAKykNUQ8AAAA=
```
output:
```
H%2B4sIAGLWTWMA%2F7NRdPF3DokMQMAKykNUQ8AAAA%3D
```
and last welcome make PRs 🥳

**Comment by RiqueAM** [comment]
forgive me I'm very noob in all this anyway, I think I'll wait for your new version, now I'm excited

**Comment by laiiihz** [comment]
next version will have this feature. by the way thanks a lot !  @RiqueAM

**Comment by RiqueAM** [comment]
let me help at least to locate in pt-BR ? where are the string language files?

**Comment by laiiihz** [comment]
cool, the file locate at https://github.com/laiiihz/alga/blob/main/lib/tools/encoders_decoders/uri_encoder_decoder/uri_provider.dart

**Comment by laiiihz** [comment]
https://github.com/laiiihz/alga/blob/main/lib/l10n/app_en.arb
@RiqueAM

**Comment by laiiihz** [comment]
copy this file and rename to app_pt_BR.arb maybe

**Comment by laiiihz** [comment]
this feature has been added. close this issue.
if have any question you can reopen this.😆
and i make a new issue #6  about other languages.

**Comment by Ahplla** [comment]
@RiqueAM u did?

**Comment by laiiihz** [comment]
> @RiqueAM u did?

i have fix the uri encode/decode issue, and im still working on #4
