### ISSUE TITLE
[Question] How does regex tester work

### ISSUE THREAD

**Issue by TheRealOne78** [laiiihz/alga#7]
I just started learning about regex and I have trouble understanding how the regex tester is supposed to work.
There is not feedback or anything to tell me what it found or what I've done right or wrong:
![Screenshot_20221213-231118.png](https://user-images.githubusercontent.com/53640879/207445100-546a8340-5c3b-4fa8-8465-af20cbd4f900.png)

**Comment by laiiihz** [comment]
your regex expression may wrong, try this:
![21671001802_ pic](https://user-images.githubusercontent.com/35956195/207529489-6b3adc8b-6b24-4246-b372-c7c2128b278e.jpg)

and sorry for no error message was displayed when typing a not valid regex expression
you can test regex expression on [regexr](https://regexr.com/), it shows some very useful infomations about regex exp.

**Comment by TheRealOne78** [comment]
Huh ya, I guess I forgot you need backslashes for this

But for some reason putting the second '\' doesn't work:
![Screenshot_20221214-091937.png](https://user-images.githubusercontent.com/53640879/207531090-b9dd27b6-84a8-43b5-8f19-a5214266a219.png)
![Screenshot_20221214-091947.png](https://user-images.githubusercontent.com/53640879/207531120-509c0b75-c32f-4d9a-9af1-0a1ac60b0d1b.png)
![Screenshot_20221214-091952.png](https://user-images.githubusercontent.com/53640879/207531140-43f5885f-5bbe-47de-839b-379c24dc607e.png)

**Comment by laiiihz** [comment]
in third picture `Hig` should match your regex.
![31671002864_ pic](https://user-images.githubusercontent.com/35956195/207532431-f7babcb2-48d9-4b19-abd5-753a1c85d3c1.jpg)

and second regex looks like not a valid regex.

**Comment by laiiihz** [comment]
may you want search text globally? this app dont need add `/g` flag.so you just write regex without `\g`

**Comment by TheRealOne78** [comment]
Oh I understand now, this app doesn't need any flags. Thank you

**Comment by laiiihz** [comment]
you‘re welcome! and if you have any issue please open new `issue`.
