### ISSUE TITLE
[feature] pure black background

### ISSUE THREAD

**Issue by nit511** [laiiihz/alga#98]
Alga uses material you theme which is good, but you can also consider adding 'pure black dark theme' feature(only in dark mode) like apps - obtainium, tachiyomi.

![Screenshot_20231124-200448_Obtainium~2](https://github.com/laiiihz/alga/assets/103308339/fb3e3535-2f87-472e-9139-94f50dac69e8)
It uses material you colors, only difference is black background.

**Comment by laiiihz** [comment]
Add this feature in #99.
